language: node_js
node_js:
- node
script:
- npm run lint
- npm run test
- npm run jest
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: LdwgIIn+96VLznvyJi8eu+D1MDZn8dYxsxXW2+U+KkSkKNNkPrAi65Dpu0clkT1wvPItAxkt098wRyX7I4VSu3+oyVfXUWGLTrlvDPGSvr+o6XQgWHy0Gju12stlITO/vJt1OKklY3x314S8HeYQdlAwZlGiCqH5owJy5nMI+iMTyhrcAstGurFRDuQ/VcyaYs4vC/0M09YKkaNbdv1526XHU6b4id9vEMHadu5fGUzKbvJkxTivleWGKZ6oB5xh+MISCgTfTtZZDfddqEjqLKSl2Tk3KjrbGY0ejbeUylJIASFOEPaAHooIkwTJcQ/hKuZiBtxPqUvjOkkfsQ44+cSMHU8Z+nhm+bS8hu3xpt2Sh5B6gX09W8QCXx8DVoe7jzFTP+vHe46jNrngDV74Kcy51JJzukJWGi6ZCWLOG7xsKuAfDC8MX502r3Z/JqvukTMPjN4VxBCbMydqGplwSFEJdGM+Hd53yYgX087zuEJLMnt0zKDwujhDbvZgkndl2hQYBKi3yZIsoJFjAjQAPUAIeOFlZ68PKhIT3/u3RzPP6889Q8EBsE6w349lnRIQZvWYu3af+L50Ho/UdArncWgCplsO9kT+4I3m9nvSkgoSTJI8Wt4SnORrxxoqWyerSZpy+XrqmeIuKRHMEOEYEdvzOMeqghG13gilE1EoBk8=
  app: yandex-image-gallery
  on:
    repo: malekylik/homework
