language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm run build
deploy:
  provider: heroku
  api_key:
  secure: "mbgBJ9KcHoUy7N7SkvsT7HilC/dyfODPD/mYXabx79cGaHxrzkwGrhZNfZ8B57jIfY154Q1Oz0xFN55iNJkeXrGT5vu6PBA2ZY0e9P2o76pdrzCk35KuDtYGEpDjSKbjQbOZK7pZdv8SyCis/WFTZmJGiCvkWFQ1R0DocYWPTop8smpo53q0PurWyIjBZInAfHVAE05Ec+fccJQtW7Nw09Wu0avzJnvfwjqbyZgOmhKC+SodCGZoWiZcY+RTXOrz7FwmgBeoqwG5RVVX/kt/8Y4nHLOnWmu9qcmoM9HaM3cG0Tm4I3bw3diyVYFBG1Iyv0a4xebEmcho0Eoq43cqDieHPzArSqKWYyIgU952khDF30i6pyUpKxm2ZGk0e1/yWie6gLKe2+/8Br+BmJhfJJtLnLRgoygzz52jx/9Sc64GJEC/qNk4Sal8H2OyFhycuDVBC2XejV/AIeUll6SElLxqyE+TV0Zw3ggt7HpWWnlYnF9p0/S8noe2wFKCASpIO23UHo5hvnuJ5cGf1Kub0eON8jQY083X64vSUtglOM6oDOe2Fh3xf+y2IkXJ5X1qq174RtkUZdGYag/FdU9xuHr7rrguxkICrCth9s50M5tFaJw0CEqz7p3SmmqmAwJDtr8GraXeEu4x2S/+Tny5Lf6OXusn9WL55T4GNwETMak="
  app: yandex-image-gallery
  on:
    repo: malekylik/homework
    